language: node_js
node_js:
  - "0.10"
services:
  - mongodb
cache:  
  directories:
    - "node_modules"
env:
  global:
    - NODE_ENV=travisci
    - BUILD_DIR=`pwd`/zpratt
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install